name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install Xvfb and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=114.0.5735.90
          wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver
          chromedriver --version
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Run tests with Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1280x1024x24 &
          sleep 3
          mvn test
      - name: Generate Allure Report
        if: always()
        run: |
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install -y allure
          allure generate target/allure-results --clean -o allure-report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots